version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: pothole-postgres
    environment:
      POSTGRES_USER: pothole
      POSTGRES_PASSWORD: pothole
      POSTGRES_DB: pothole
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: pothole_minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command:
      [
        "server",
        "/data",
        "--address",
        "0.0.0.0:9000",
        "--console-address",
        ":9001",
      ]
    restart: unless-stopped

  kestra:
    image: kestra/kestra:latest
    container_name: pothole_kestra
    user: "root"
    ports:
      - "8080:8080"
    volumes:
      - kestra_data:/app/storage
    command: ["server", "local"]
    restart: unless-stopped

volumes:
  postgres_data:
  minio_data:
  kestra_data:
